spring:
  application:
    name: books-demo

greeting:
  message: Hello world

info:
  contact:
    phone: 123-123-1234
    email: support@example.org
  fax: 321-321-3214
  name: ${spring.application.name:i-dunno}
  
management:
  info:
    git:
      mode: full
  
  endpoint:
    health:
      show-details: always
      
  endpoints:
    web:
      exposure:
        include: '*'

---
spring:
  profiles: stl
  
greeting:
  message: Hello St. Louis
  
---
spring:
  profiles: iad
  
greeting:
  message: Hello Reston