message:
  who: UberConf X (2019)
  
  
info:
  support:
    email: support@example.com
    phone: 123-123-1234
  fax: 321-321-${local.server.port}
  
management:
  info:
    git:
      mode: full
      
  endpoint:
    health:
      show-details: always
      
  endpoints:
    web:
      exposure:
        include: '*'
        exclude:
        - heapdump

spring:
  boot:
    admin:
      client:
        url: http://localhost:9999
  data:
    rest:
      base-path: /api
     
  jpa:
    show-sql: true
---
spring:
  profiles: austin
  
message:
  who: Lone Star Software Symposium Austin