greeting:
  message: Hello NFJS!
  other: other

info:
  contact:
    email: support@example.com
    phone: 123-123-1234
  fax: 321-321-3210
  
management:
  info:
    git:
      mode: full

  endpoint:
    health:
      show-details: always
      
  endpoints:
    web:
      exposure:
        include: '*'

---
spring:
  profiles: msp
  
greeting:
  message: Hello MSP!  

---
spring:
  profiles: ord

greeting:
  message: Hello ORD!