greeting:
  message: Hello World!

management:
  endpoints:
    web:
      exposure:
        include: '*' 
        
info:
  contact:
    phone: 123-123-1234
    email: support@help.com
  fax: 321-321-3210
---
spring:
  profiles: uberconf
  
greeting:
  message: Hello UberConf!
 
  
---
spring:
  profiles: springone
  
greeting:
  message: Hello SpringOne