spring:
  application:
    name: books-cmh
     
  boot:
    admin:
      client:
        url: http://localhost:9090
     
  data:
    rest:
      base-path: /api

  jpa:
    show-sql: true
     
greeting:
  where: World
  
  

info:
  name: ${spring.application.name}
  contact:
    email: support@example.com
    phone: 123-123-1234
  fax: 321-321-3214

management:
  info:
    git:
      mode: full
      
  endpoint:
    health:
      show-details: always
      
  endpoints:
    web:
      exposure:
        include: '*'

---
spring:
  profiles: cmh
  
greeting:
  where: Columbus

---
spring:
  profiles: dfw
  
greeting:
  where: Dallas
  