server:
  port: 0

greeting:
  message: Hello World!

spring:
  boot:
    admin:
      client:
        url:
        - http://localhost:9999

info:
  contact:
    phone: 123-123-1234
    email: support@example.com
  fax: 321-321-3210
  greeting: ${greeting.message}

management:
  info:
    git:
      mode: full
  endpoint:
    health:
      show-details: always
      
  endpoints:
    web:
      exposure:
        include: '*'
        exclude:
        - heapdump


---
spring:
  profiles: bos
  
greeting:
  message: Hello Boston!  

---
spring:
  profiles: msp
  
greeting:
  message: Hello Minneapolis!
