server:
  port: 8081


spring:
  application:
    name: Madison NFJS Books Sample
  boot:
    admin:
      client:
        url: http://localhost:9999

info:
  api-name: ${spring.application.name}
  support:
    phone: 123-123-1234
    email: support@example.com
    fax: 321-321-3210
  hours:
    start: 9:00am
    end: 5:00pm

logging:
  level:
    com.zaxxer.hikari: ERROR


management:
  info:
    git:
      mode: full
      
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
        exclude:
        - heapdump
        
