server:
  port: 8080
  
info:
  contact:
    phone: 123-123-1234
    email: support@example.com
  fax: 321-321-3210
    
management:
  endpoints:
    web:
      exposure:
        include: '*'
        
  info:
    git:
      mode: full
      
  endpoint:
    health:
      show-details: always