greeting:
  message: Hello, World!
  
info:
  contact:
    phone: 123-123-1234
    email: support@example.com
  fax: 321-321-3210
  
spring:
  jpa:
    show-sql: true  
  
management:
  info:
    git:
      mode: full
      
  endpoint:
    health:
      show-details: always
      
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: heapdump
  
---
spring:
  profiles: iad
  
greeting:
  message: Hello, Reston!
  random: ${random.int} 
  
---
spring:
  profiles: sea
  
greeting:
  message: Hello, Seattle!
  random: ${random.int}