

greeting:
  message: Hello World!

info:
  contact:
    phone: 123-123-1234
    email: support@example.com
  fax: 321-321-3210
  greeting: ${greeting.message}
  
management:
  info:
    git:
      mode: full
  endpoint:
    health:
      show-details: always
      
  endpoints:
    web:
      exposure:
        include: '*'
        exclude:
        - heapdump
        
spring:
  boot:
    admin:
      client:
        url:
        - http://localhost:9999
  application:
    name: aus-books
    
  data:
    rest:
      base-path: /api
  jpa:
    show-sql: true  
---
spring:
  profiles: austin
  
greeting:
  message: Howdy Austin!
  
server:
  port: 9191
  
---
spring:
  profiles: desmoines
  
greeting:
  message: Hiya Des Moines!

  
 