apiVersion: apps/v1
kind: Deployment
metadata:
  name: books-k8-deploy
  labels:
    app: k8s-books
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-books
  template:
    metadata:
      labels:
        app: k8s-books
    spec:
      containers:
      - name: books-k8s-container
        image: habuma/uberbooks
---
apiVersion: v1
kind: Service
metadata:
  name: books-svc
  labels:
    app: k8s-books
spec:
  type: NodePort
  ports:
  - port: 31234
    nodePort: 30123
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: k8s-books
