spring:
  application:
    name: Books
    
    
info:
  greeting: Hello Boston!
  contact:
    phone: 123-123-1234
    email: craig@habuma.com
    
management:
  info:
    git:
      mode: full
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'

---
spring:
  profiles: prod
  
info:
  greeting: Hello production!!!
