spring:
  application:
    name: DSM-Books

  boot:
    admin:
      client:
        url:
        - http://localhost:9999

greeting:
  who: World
  
info:
  support:
    phone: 123-123-1234
    email: support@example.com
  fax: 321-321-3210
  other:
    greeting: ${greeting.who}
    name: ${spring.application.name}

management:
  info:
    git:
      mode: full
      
  endpoint:
    health:
      show-details: always
      
  endpoints:
    jmx:
      exposure:
        include:
        - hiya
    web:
      exposure:
        include: '*'
        exclude:
        - heapdump

---
spring:
  profiles: dsm
  
greeting:
  who: Des Moines
  
---
spring:
  profiles: aus
  
greeting:
  who: Austin