spring:
  application:
    name: profiles

  jpa:
    show-sql: true


logging:
  level:
    org.springframework.security: debug


management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    git:
      mode: full
      
  endpoint:
    health:
      show-details: always
        
info:
  contact:
    phone: 123-123-1234
    email: support@helpme.com
  fax: 321-321-3210
  
greeting:
  message: Hello there

  