server:
  port: 0

spring:
  cloud:
    stream:
      bindings:
        input:
          destination: names
        output:
          destination: greeted
          content-type: text/plain
  application:
    name: hello-sayer

