spring:
  application:
    name: books-msp
  boot:
    admin:
      client:
        url:
        - http://localhost:9999

greeting:
  message: Hello World

info:
  contact:
    phone: 123-123-1234
    email: support@example.com
  fax: 321-321-3210
  salutation: ${greeting.message}
  
management:
  info:
    git:
      mode: full

  endpoint:
    health:
      show-details: always

  endpoints:
    web:
      exposure:
        include: '*'
        exclude:
        - heapdump

fake:
  password: shouldntseethis
  

---
spring:
  profiles: msp
  
greeting:
  message: Hello Minneapolis
  

---
spring:
  profiles: aus
  
greeting:
  message: Hello Austin
  