greeting:
  message: Hello, NFJS!
  
server:
  port: 9090
  
management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    git:
      mode: full
        
        
info:
  contact:
    phone: 123-123-1234
    email: support@example.com
  fax: 321-321-3210
  

  
---
spring:
  profiles: chicago
  
greeting:
  message: Hello, Chicago!!!!!!!!
  
---
spring:
  profiles: reston
  
greeting:
  message: Hello, Reston!
  