spring:
  application:
    name: books-iad

hello: Hello NFJS!

greeting:
  message: ${hello} 
  
info:
  name: ${spring.application.name}
  contact:
    phone: 123-123-1234
    email: support@example.org
  organization:
    manager: Chris W.
  
management:
  info:
    git:
      mode: full
      
  endpoint:
    health:
      show-details: always
      enabled: true
      
  endpoints:
    web:
      exposure:
        include: '*'


        
  
---
spring:
  profiles: iad

greeting:
  message: Hello Reston NFJS!
  place: fjdsofjdkl
  
---
spring:
  profiles: stl 

greeting:
  message: Hello St. Louis NFJS!
---
spring:
  profiles: production
   
  datasource:
    url: hfjkdlhfjkdsl
    